name: generated ASCII Artwork

on: 
    push

jobs: 
    ascii-job:
         runs-on: ubuntu-latest
         steps: 
            - name: checkout Repo
              uses: actions/checkout@v4

            
            - name: checkout Repo files
              run: ls 
             
            - name: executing shell script
              run: | 
                  chmod +X  ./ascii-script.sh
                   ./ascii-script.sh