name: matrix check

on:
 push

concurrency:
  canel-in-progress: true
  group: matrix

jobs: 
 deploy-in-windows:
   runs-on: windows-latest 
   steps:
      - name: docker info
        run: docker info
      - name: run the container
        run: docker run hello-world 
 deploy-in-linux: 
   runs-on: ubuntu-latest 
   steps: 
     - name: docker info 
       run: docker info 
     - name: run the container 
       run: docker run hello-world